# Site settings
title: Saint Benedict the African Parish
email: SBAparish@aol.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://benedicttheafrican.org" # the base hostname & protocol for your site

permalink: pretty

twitter_username: #
github_username: #

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

# Google Analytics
google_analytics: UA-140674991-1