# Site settings
title: Saint Benedict the African Parish
email: SBAparish@aol.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/sba" # the subpath of your site, e.g. /blog/
url: "https://villasite.github.io/sba" # the base hostname & protocol for your site

twitter_username: #
github_username: #

# Build settings
markdown: kramdown
